### ISSUE TITLE
[Domain Model] ¿Solo un barter por usuario?

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#10]

**Comment by CeuxDruman** [comment]
No, finalmente son varios. Se puede ver, por ejemplo, en el requisito: "Any user can create a match between any of the barters has he or she’s registered"

**Comment by ManuelLR** [comment]
@CeuxDruman No lo veo claro ahí, preguntaría a Inmaculada mañana
