### ISSUE TITLE
SocialIdentity falla en la paginación (al pasar a página 2)

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#110]
Concretamente se te va a la pagina principal de la app.

**Comment by ManuelLR** [comment]
@CeuxDruman Poncaso exacto si no te importa  que hay varias maneras de acceder a esa vista

**Comment by CeuxDruman** [comment]
@ManuelLR Logeo como user1 > pestaña del menu con su nombre de usuario > profile info > Social Identity: display 

Una vez en la vista pasas a la pagina 2 y peta (peta = te sale al inicio/home)

**Comment by CeuxDruman** [comment]
@ManuelLR Te subo a Develop si quieres lo que llevo para que puedas probarlo (si lo vas a probar ahora)

**Comment by ManuelLR** [comment]
@CeuxDruman Tranquilo que estoy a punto de dormir, solo te lo comenté porque ahora lo sabrías responder y mañana no
