### ISSUE TITLE
Lista de Barters duplicada ?!

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#112]
Te logueas como Admin y hay 2 vistas para listar Barters "iguales":
Menu "Gestionar" -> "Trueques": Lista los Barters cancelados o no.
Menu "Listar" -> "Trueques": Lista sólo los Barters no cancelados.

Quien lo haya hecho que se ponga de acuerdo y no haya 2 vistas duplicadas, controladores duplicados etc...

**Comment by guillermo-ag-95** [comment]
He quitado el enlace del header de la master page
