### ISSUE TITLE
¿Dónde está la opción para que un Auditor se asigne un Match?

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#113]
La vista sólo muestra los Matchs que tienes asignados, pero no hay ningún botón para asignarte un nuevo Match ni una vista de Match no asignados con botones en la tabla para asignartelo ni nada.

**Comment by ManuelLR** [comment]
@CeuxDruman No hay ningún requisito de muéstrame todos los match para poder asignarlos por lo que la manera de asignarlos es que vaya a un usuario, muestre sus matchs y se lo asigne

**Comment by CeuxDruman** [comment]
Se hace desde otra vista.
