### ISSUE TITLE
El boton de cancelar de la vista de editar informacion no devuelve al display

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP10Entrega#124]
Deberia volver a la vista anterior, pero vuelve al inicio

**Comment by ManuelLR** [comment]
Mejor dejarlo así ya que se usa en muchos sitios y podemos generar errores no deseados

**Comment by ManuelLR** [comment]
todos de acuerdo?

**Comment by migrodcab** [comment]
Ok
