### ISSUE TITLE
[Service] Error en userService.getUsersWithNoBarterThisMonth()

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#125]
Este método no devuelve lo que se espera, puede comprobar al lanzar el test UserServiceTest.testUsersNotCreateRecentBarter()

igualmente ese servicio usa cosas deprecated, por favor mirad lo del test que cumple de mejor manera los requisitos

**Comment by guillermo-ag-95** [comment]
Solucionado d93c78f
