### ISSUE TITLE
OJO!! Se pueden cancelar Barters cuando no debería

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP10Entrega#130]
He podido cancelar un Barter que estaba en un match activo

**Comment by ManuelLR** [comment]
eso debe ser posible, no debería de dejarte solo en caso de que ese match ya esté firmado

(si se dan cuenta de que vendes drogas... solo por haberle pedido a alguien que te haga el cambio no va a ser posible cancelarlo?)

**Comment by migrodcab** [comment]
@ManuelLR Ok, menos problemas

**Comment by ManuelLR** [comment]
prueba que no te deje cuando esté firmado a ver si es que tampoco está cubierto xD

**Comment by migrodcab** [comment]
@ManuelLR eso deberia hacerlo el que haga las pruebas de barter

**Comment by guillermo-ag-95** [comment]
Según Carlos, se puede cancelar siempre
