### ISSUE TITLE
[Test] Fallos encontrados por mis test

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP10Entrega#132]
- En testLegalTextFindAll2 puedes listar los legalText sin ser admin. Esto no se puede hacer en la página pero en los servicios si se puede hacer. Si se va a cambiar, estad seguro de que no afecte a otras vistas.

**Comment by migrodcab** [comment]
Ojo, un user tambien puede hacer un findAll, no solo un admin
