### ISSUE TITLE
Duda al relacionar Barters

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP10Entrega#133]
Solo hay un select en el que eliges los barters a relacionar, pero el problema es:
1.- Entras y eliges Barters 1 y 2 para estar relacionados
2.- Olvidas que tambien querias relacionar el 3
3.- Vuelves a editar los barters relacionados y en el select ya no están los barters 1 y 2. Eliges el barter 3
4.- Ahora esta relacionado con el Barter 3 pero no con el 1 y el 2
La collecion de barters que se le pasa al select no seria mejor un findAllNotCanceled()?

**Comment by ManuelLR** [comment]
el tema de relacionar los barters hay que crearlo desde cero como he dicho en el issue #129
