### ISSUE TITLE
Cambiar/Quitar Rol Barter

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#15]
De "barter" 1 a "relatedBarter" 0..*.

El rol "barter" es scaffolding, un rol no puede tener el mismo nombre que la entidad.

Mi propuesta es quitar el rol y dejar como denominación el propio nombre de la clase. Si se nos indica que en una relación de tipo bucle es estrictamente necesario que ambo sentidos tengan un rol habría que discutir/buscarle un nombre.

**Comment by ManuelLR** [comment]
Relacionado con #14 
Quizás sea útil solucionarlos a la vez.

**Comment by ManuelLR** [comment]
Un rol ya está puesto
