### ISSUE TITLE
Relación entre User - User

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#16]
Ventajas y Desventajas de cada propuesta **según mi opinión (Comentad las vuestras y mañana se exponen todas a Inma).**

Mi propuesta 1 es:

followed 0..\* X  ------------- > 1 follower

Desventajas: No le veo ninguna.
Ventajas: 
-Sin necesidad de ser bidireccional.
-Sin necesidad por lo tanto de guardar más datos de los necesarios ni crear tablas secundarias extras en la BBDD.

Mi propuesta 2 es:
Puesto que la propuesta 1 no estoy seguro de cómo sería en cuanto a implementación, puesto que es la primera vez que se presentaría un caso como este, en el caso de que no fuera posible propondría hacerlo bidireccional:

followed 0..\* <  ------------- > 1 follower

Desventajas: Es bidireccional
Ventajas: 
-Ahora sí permitiría el acceso navigable a los que sigues.

-Ventajas de mis propuestas 1 y 2: Con saber a los que tú sigues no necesitas tener guardado explícitamente quién te sigue a ti, puesto que comprobando a quién sigue cada usuario puedes ver si te encuentras en sus "listas" y así ver quién te sigue.

---

Propuesta de @ManuelLR 

followed 0..\* < ------------- > 0..\* follower

Desventajas:
-Bidireccional, por lo que se guardan datos "duplicados".
-0..\* <--> 0..*: Necesita de clase intermedia = más almacenamiento extra
Ventajas: No le veo ninguna.

**Comment by ManuelLR** [comment]
@CeuxDruman Creo que es un buen tema a discutir mañana en clase

**Comment by ManuelLR** [comment]
Seleccionada:

followed 0..\* < -----------X--  0..\* follower
