### ISSUE TITLE
Repartir tareas (absolutamente todo) 

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#18]

**Comment by guillermo-ag-95** [comment]
El reparto está hecho en el Statement y las pruebas seguirán el esquema de las pruebas de Acme Six-Pack https://github.com/DPIRPSG/DP10Entrega/commit/7981e607558e44ebd4787dc06edd7ed625e67e02

Falta el reparto de las pruebas funcionales.
