### ISSUE TITLE
¿Que pasa cuando alguien te asocia un match cuando no viene a cuento? 

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#19]
Ejemplo:
Tengo un barter de portátil por iPhone y alguien me asocia un match con un barter que tiene un peine por portátil. Evidentemente el usuario original cancelará el match pero su barter dejará de ser utilizable. ¿Tendrá que crear otro de nuevo (será su decisión) ? ¿Lo creará el programa automáticamente? Carece de sentido ese apartado si no se le da matices

**Comment by guillermo-ag-95** [comment]
Se cancela el match y punto. Esto queda especificado en la actualización del Statement del Jueves 7 de Abril de 2016.

https://github.com/DPIRPSG/DP10Entrega/issues/20
