### ISSUE TITLE
Que Guille se ponga Alias en Telegram!!!

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP10Entrega#2]

**Comment by CeuxDruman** [comment]
Adjunto la nueva etiqueta "UML" ante la grave falta de la misma en este asunto con gravedad y urgencia máxima.

**Comment by ManuelLR** [comment]
Aparentemente solucionado

**Comment by CeuxDruman** [comment]
@guillermo-ag-95 (alias @guillermoag95 ) Cierralo cuando lo veas oportuno.
