### ISSUE TITLE
[Domain Code] Cambiar relacion Barter-Match a 0..*

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#21]
- Un Barter no puede estar implicado en mas de un match si todos menos uno se cancelan

**Comment by ManuelLR** [comment]
Está cambiado en el domainCode desde hace tiempo. (Fue antes de la revisión). Falta tenerlo en cuenta en el servicio y añadir la posible nota en el UML en caso de que no esté añadida

**Comment by CeuxDruman** [comment]
En el servicio y en el UML ya estaban tenidos en cuenta.
