### ISSUE TITLE
Priority mejor como enumerado que como número según Inma

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#26]

**Comment by ManuelLR** [comment]
Mejor dejarlo como está y gestionarlo nosotros.... por cierto te cambio anumerado como enumerado

**Comment by CeuxDruman** [comment]
No entiendo por qué dices que es mejor, pero si al Manager ( @migrodcab ) le parece bien palante xD

**Comment by ManuelLR** [comment]
@CeuxDruman Más sencillo, menos complicaciones y en clase dijo que era mejor pero dijimos de dejarlo así

**Comment by migrodcab** [comment]
@CeuxDruman Si inma dijo que mejor así, pues así

**Comment by CeuxDruman** [comment]
@ManuelLR pero si dijo Inma todo lo contrario xd Que es mucho más sencillo como enumerado porque si en un futuro hay que extender el priority a otras entidades (no se si era un guiño) sería mucho más sencillo.

Dijimos de comentarlo entre todos y por eso se creó este Issue por cierto xD

**Comment by ManuelLR** [comment]
Yo opino que no, y así está implementado, si alguien piensa que es de otra manera es libre de pelearse con los mensajes xD
