### ISSUE TITLE
[Domain Code] Renombrar nombres x, y

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#5]
Cambiar en UML y domain

**Comment by CeuxDruman** [comment]
x = offerer
y = requester

@ManuelLR FALTA EN JAVA DOMAIN

**Comment by ManuelLR** [comment]
@CeuxDruman No falta ya que esa relación está puesta como unidireccional

**Comment by CeuxDruman** [comment]
@ManuelLR Tal y como dijo @migrodcab por el grupo: Hace falta aunque sea unidireccional porque en el Conceptual Model eso de que sea unidireccional para justificarlo no se ve ni se puede justificar de ninguna manera.

También puedes comprobarlo en las transparencias de cualquier asignatura en la que hemos dado modelado UML. Por ejemplo en la Diap. 7 del tema 8 de IR.

**Comment by CeuxDruman** [comment]
@ManuelLR Vale, no he dicho nada, he entendido mal tu comentario. Efectivamente en el modelo Java no hace falta. Cierro Issue.

**Comment by ManuelLR** [comment]
Digo que no falta en el java domain ya que al ser unidireccional solo se pone en una de las clases implicadas por lo que en ningún momento es posible poner ese nuevo nombre de "x"  e "y".
Dicho en otras palabras, ítem no contiene ningún collection<Barter> por lo que no es posible llamar a esa variable "x" o "y"

**Comment by ManuelLR** [comment]
@CeuxDruman OK xD
