### ISSUE TITLE
[Ubicación incorrecta] BarterUserController

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#52]

**Comment by migrodcab** [comment]
Por que? está en el paquete de customer.

**Comment by ManuelLR** [comment]
@migrodcab Te recuerdo que ahora es user no customer. No lo quise mover por si lo estabas usando

**Comment by migrodcab** [comment]
@ManuelLR Lo que hay que hacer es renombrar ese paquete a user

**Comment by ManuelLR** [comment]
@migrodcab Solo queda ese paquete

**Comment by ManuelLR** [comment]
@ManuelLR Esa clase***
