### ISSUE TITLE
No volver a Manolo loco con los Issues

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#57]
Decidid que queréis que haga 
- #46 
- #39

**Comment by migrodcab** [comment]
@ManuelLR Yo sigo pensando que lo del #39 no es, que solo fue una errata ya que en todo el statement les llama siempre user

**Comment by ManuelLR** [comment]
@migrodcab Yo pienso lo mismo la verdad

**Comment by CeuxDruman** [comment]
A ver, en el proyecto no hay que tocar nada. Simplemente en los UML se pone el rol "customer", que sólo indica que el cliente a los Users también les llama a veces Customer. Pero no hay que tocar nada del código. Mientras que no se nos diga que es una errata debe estar o será un fallo. Pero para eso puse el "Ask in class". De manera que si Inma afirma que es una rata lo quitamos, y si no ponemos el rol en UMLs (repito que no afecta al código).

**Comment by CeuxDruman** [comment]
Era una errata (By Inma)
