### ISSUE TITLE
Que a un User no le aparezca el enlace de seguirse a si mismo

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP10Entrega#62]
Es tan simple como en el controller pasarle su id por un parametro con el findByPrincipal y en la vista un if para que no lo muestre si es igual al row_user.id

**Comment by ManuelLR** [comment]
@migrodcab Ok, gracias por ponerlo como issue
No lo quise solucionar desde el principio por si se me ocurría otra forma de hacerlo más optimo ya que este parámetro se le deberá pasar por dos controladores distintos. De todas formas implementaré esa solución porque creo que no hay otra
