### ISSUE TITLE
Si un match está cancelado... ¿Un auditor podría escribir un report?

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#64]

**Comment by CeuxDruman** [comment]
En este tema de los Match hay muchas cosas a interpretación y que no influyen en el funcionamiento ni las normas. Esta es una de ellas y da lo mismo si lo permites como si no, podría tener sentido en ambos casos.

**Comment by ManuelLR** [comment]
Resuelto en clase.
Se debe permitir para facilitar todo
