### ISSUE TITLE
Quitar NotBlank al Report de Match

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#67]
Está cambiado en Java, falta en los UMLs.

Razón del cambio: Desde la vista un "null" se pasa como "", por lo que aunque esté el Report a null desde Java, a la hora de comprobar sus errores de validación salta el NotBlank.

**Comment by ManuelLR** [comment]
@CeuxDruman No se puede hacer como dices, si no no cumple los requisitos, se debería sobrescribir en el save para que cumpla

**Comment by CeuxDruman** [comment]
@ManuelLR ¿qué requisito dice que tenga que ser NotBlank? Los report son totalmente opcionales.

Además eso del save ya lo he hecho y no sirve de nada, los errores de validación se comprueban antes de hacer el save precisamente.

**Comment by ManuelLR** [comment]
@CeuxDruman Bueno, haz lo que veas

**Comment by CeuxDruman** [comment]
@ManuelLR Lo que vea no xd Si hay un requisito que exija ser NotBlank dilo.

**Comment by ManuelLR** [comment]
@CeuxDruman No hay ningún requisito en estos entregables que exija que algo no pueda estar en blanco xD

**Comment by CeuxDruman** [comment]
@ManuelLR pues eso xD

**Comment by migrodcab** [comment]
@CeuxDruman Un report no debe tener ni @NotNull ni @NotBlank ya que cuando se crea un match el campo esta vacío hasta que un Auditor se lo asigna y lo escribe xd

**Comment by ManuelLR** [comment]
@migrodcab ojo, una cosa es NotNull y otra NotBlank

**Comment by CeuxDruman** [comment]
@ManuelLR Ya, manolo. Pero, ¿Has leído la descripción del Issue?

**Comment by guillermo-ag-95** [comment]
Ya está 6914d57
