### ISSUE TITLE
[Service] Incumplimiento requisitos BarterService.cancel

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#68]
https://github.com/DPIRPSG/DP10Entrega/blob/Develop/WorkSpace/Acme-Barter/src/main/java/services/BarterService.java#L110-L121

El problema está en que no solo puede hacerlo un admin según hablamos con Inma (#22)

**Comment by ManuelLR** [comment]
Reitero, esto sigue fallando

**Comment by guillermo-ag-95** [comment]
Ya lo he corregido 07f9320

Falta comprobar con los test que funciona bien bien
