### ISSUE TITLE
Para el PostHacking...

### ISSUE THREAD

**Issue by migrodcab** [DPIRPSG/DP10Entrega#76]
Que veis mejor, ¿Controlarlo en el servicio o hacer que pete con un assert?

**Comment by ManuelLR** [comment]
@migrodcab Mejor que no pete y se cambie, yo lo prefiero es más fácil de hacer y la aplicación no da error

**Comment by ManuelLR** [comment]
@ManuelLR Porque pienso esto? Primero comodidad para nosotros, es decir, cogemos el objeto que nos viene y lo buscamos por el id, por ese podemos comprobar que efectivamente podía cambiarlo (por ejemplo, por postHackimg podrían editar el usuario de un Barter y tu lo guardarías porque todo concuerda pero el original de la base de datos en realidad es propiedad de otro) y porque nosotros mediante un set le cambiamos lo que realmente puede editar evitando llenar los métodos de asserts. Yo solo le veo ventajas, claro, no da error pero efectivamente no realiza ese cambio. Para probar es una lata pero es más sencillo en general

**Comment by CeuxDruman** [comment]
No entiendo, ¿estás diciendo que es más sencillo hacer que cada atributo cambie a un valor correcto en cada caso en vez de poner 1 linea de Assert y despreocuparte por lo que debe devolver? XD ¿Qué ventajas tiene ponerte a pensar y hacer eso si lo único que va a hacer es que la aplicación no le pete a los hackers pero a nosotros dificultarnos la vida para los test, en los que tenemos que estudiarnos todo el código del resto y cambiar los test de negativos a positivos en dichos casos y no solo eso si no tener que hacer más test de la cuenta para que se cumpla que haya 2 negativos en cada caso?
