### ISSUE TITLE
¿Sólo con enviar un mensaje a Spam ya se considera "marcado como spam"?

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#84]

**Comment by ManuelLR** [comment]
Yo creo que es así pero se puede preguntar a Inma.

Yo lo que entiendo es solamente añadir a la carpeta.

**Comment by ManuelLR** [comment]
1. Botón de mandar a Spam
2. Cuando lo manda a Spam lo quita de las otras carpetas

_**Mejoras**_
1. ¿Desmarcar de Spam?
2.

**Comment by ManuelLR** [comment]
implementado sin las mejoras
