### ISSUE TITLE
Controlar escribir un Report a un Match no asignado a nadie

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP10Entrega#85]
Si un auditor intenta escribir un Report a un Match no asignado a nadie no se completa la operación, pero salta un NullPointerException en vez de el correspondiente Assert de que no lo tengas asignado a ti, que compruebas que seas tú el auditor asignado, pero no que el auditor asignado no esté a null.

**Comment by ManuelLR** [comment]
No entiendo, no lo controlo aquí:
https://github.com/DPIRPSG/DP10Entrega/blob/Develop/WorkSpace/Acme-Barter/src/main/java/services/MatchService.java#L302 ????

**Comment by ManuelLR** [comment]
Comprueba que se cumple ya porfa

**Comment by CeuxDruman** [comment]
Confirmado.
