### ISSUE TITLE
[Domain Model] ¿¿Cambiar messageBox por folder??

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#9]

**Comment by CeuxDruman** [comment]
No entiendo. En el UML ya está como Folder (Y así ha estado siempre). Sólo que tiene message box como rol.

**Comment by ManuelLR** [comment]
@CeuxDruman Exacto, el rol y en esta no hay nada que haga referencia a ese nombre de rol en ningún lado

**Comment by CeuxDruman** [comment]
Requisito 10.3 del C: Manage his or her messages and **message boxes**.

**Comment by ManuelLR** [comment]
@CeuxDruman Gracias, que no lo encontraba el otro día xD
