### ISSUE TITLE
ERROR en un barter.getRelatedBarter contiene null ! !

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP10Entrega#96]
Mirar porque pasa y como

**Comment by migrodcab** [comment]
@ManuelLR Podrías explicar un poco más el

**Comment by migrodcab** [comment]
@migrodcab Fallo*

**Comment by ManuelLR** [comment]
coges un barter cualquiera haces .getRelatedBarter y esa lista contiene barters y nulls

**Comment by ManuelLR** [comment]
Falta revisar que, efectivamente no pasa.
